name: Zan1271
rank: Owner
version: 1.16.200
Enjoy The Game

virions:
- ScoreFactory
- UpdateNotifier
- ConfigUpdater

permissions:
  sh.command.sh:
    default: true
    description: Allow players to use /scorehud command.
